apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: by-homeassi-poi-map-app-dev
  annotations:
    argocd/app-name: by-homeassi-poi-map-app-dev
    backstage.io/kubernetes-id: by-homeassi-poi-map-app
    backstage.io/kubernetes-namespace: by-homeassi
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/by-homeassi-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/by-homeassi/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/by-homeassi/deployments/by-homeassi-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/by-homeassi-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://by-homeassi-poi-map-app-by-homeassi.apps.rosa-pzz6v.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/by-homeassi"
  system: workshop-system-by-homeassi
  consumesApis:
    - gateway-api-by-homeassi
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-by-homeassi
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/by-homeassi"
